services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: app
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./requirements.txt:/requirements.txt
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: db
    env_file:
      - db/.env
    ports:
      - 5432:5432
    volumes:
      - ./db/eternal:/var/lib/postgresql
volumes:
  eternal:
