services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - AUTHLIB_INSECURE_TRANSPORT=true
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./requirements.txt:/requirements.txt
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: db
    env_file:
      - db/.env
    volumes:
      - ./db/eternal:/var/lib/postgresql
  sample-sp:
    build:
      context: .
      dockerfile: sample-sp.Dockerfile
    container_name: sample-sp
    ports:
      - 3000:3000
    volumes:
      - ./sample-sp:/sample-sp
volumes:
  eternal:
